name: Build, Push & Deploy Backend to GKE

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      # Assuming GCR. Update if you use Artifact Registry (e.g., region-docker.pkg.dev)
      GCP_REGISTRY_HOSTNAME: gcr.io 
      # Placeholder for the image repository path (e.g., 'backend-app')
      GCP_REPO_NAME: my-backend-repo 
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        # This action securely uses the raw JSON content from your GCP_SA_KEY secret
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker configuration for pushing images
        # Configures Docker to use the authenticated gcloud credentials
        run: gcloud auth configure-docker ${{ env.GCP_REGISTRY_HOSTNAME }}

      - name: Set image name with version
        id: vars
        run: |
          # The REPO_PATH for GCR/Artifact Registry often includes the project ID and a repository name
          REPO_PATH="$GCP_PROJECT_ID/$GCP_REPO_NAME" 
          APP_NAME=$(basename $GITHUB_REPOSITORY) # e.g., 'Backend-Deploy-GKE-Cluster'
          
          if [ -f backend/VERSION ]; then
            VERSION=$(cat backend/VERSION)
          elif [ -f backend/package.json ]; then
            VERSION=$(jq -r '.version' backend/package.json)
          else
            VERSION="0.0.1"
          fi
          
          # Final image path: REGISTRY_HOSTNAME/PROJECT_ID/REPO_NAME/APP_NAME:VERSION
          IMAGE_NAME="$GCP_REGISTRY_HOSTNAME/$REPO_PATH/$APP_NAME:$VERSION"
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "Image to be used: $IMAGE_NAME"

      - name: Build and Push Docker image
        run: |
          docker build ./backend -t ${{ steps.vars.outputs.image_name }}
          docker push ${{ steps.vars.outputs.image_name }}

      - name: Get GKE credentials
        # This action fetches GKE credentials and ensures kubectl is installed
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          # Substitute the image placeholder in your deployment YAML
          sed -i "s|IMAGE_PLACEHOLDER|${{ steps.vars.outputs.image_name }}|g" backend/deployment.yaml
          
          # Apply the configuration to the GKE cluster
          kubectl apply -f backend/deployment.yaml
          
          # Wait for the deployment to complete
          kubectl rollout status deployment/backend-deployment --namespace=default