name: Build & Push Backend to GKE

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GCP credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io

      - name: Build Docker image
        run: |
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend"
          docker build -t "$IMAGE_NAME:latest" -t "$IMAGE_NAME:${{ github.sha }}" ./backend

      - name: Push Docker image
        run: |
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend"
          docker push "$IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:${{ github.sha }}"

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
            --zone ${{ secrets.GKE_ZONE }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Deploy backend to GKE using manifest
        run: |
          # Replace image tag dynamically in the manifest before applying
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:${{ github.sha }}"
          sed -i "s|IMAGE_PLACEHOLDER|$IMAGE|g" backend/deployment.yaml

          kubectl apply -f backend/deployment.yaml
          kubectl rollout status deployment/backend-deployment --namespace=default
